test/project-chunking/expected.js

Fixes #5.
The issue seems to be that we're comparing the exact webpack output and asset ordering, where the webpack output might vary between platforms, and the asset ordering does change depending on subtle promise timings.
Hopefully this should reduce those reliances, but lets see how the CI looks.

Handle timing / platform variations in project test

---

src/asset-relocator.js
test/index.test.js
test/unit/syntax-err/input.js

This fixes the issue of parser rejection errors not being correctly propagated back to Webpack.
In addition, the asset relocator has a filter regex it uses to determine if a full parse and analysis is needed or not. Due to the lack of the use of word boundaries, this is still overclassifying. So I've restricted the word boundaries a little that should aid in performance as well.
Fixes #7

Ensure parser errors are properly returned

---

src/asset-relocator.js
test/index.test.js
test/unit/express-template/input.js
test/unit/express-template/output-coverage.js
test/unit/express-template/output.js

This provides support for the express template pattern, as described in https://github.com/zeit/ncc/issues/323#issuecomment-475627822.
Note how small the code diff is, due to the levels this analysis is getting to :)
Also note that the analysis is resiliant to variations (eg destructuring / ES modules v CommonJS modules etc)!

Handle express templates

---

src/utils/special-cases.js
test/unit/google-gax2/input.js
test/unit/google-gax2/output-coverage.js
test/unit/google-gax2/output.js

Fixes #330, by ensuring that we clear the AST so that it doesn't attempt to apply the asset relocator twice over the same source location giving the magic string chunking error.
Test included for the bug case.

Fix google-gax double replacement bug

---

src/asset-relocator.js
test/unit/bindings-failure/input.js
test/unit/bindings-failure/output-coverage.js
test/unit/bindings-failure/output.js

This PR includes support for bindings analysis failures to ensure the build can continue.
This fixes zeit/ncc#334 where the fallback path analysis will cause a failure that isn't a runtime failure.

Support bindings failures

---

src/asset-relocator.js
src/utils/special-cases.js

This fixes up the binary path to OracleDB, and also fixes the test failure for the pkginfo feature, which should have failed on the original PR. Perhaps we didn't wait for CI to complete on the second run?

Oracledb fix

---

package.json
src/asset-relocator.js
src/utils/merge-source-maps.js

This PR handles input source map passing as well as the chaining of source maps when the asset source maps apply after a previous transformation.
Integration test to be included in the corresponding ncc PR.
Further unit tests can be provided, and coverage improved over time, but for now I just wanted to get something up and going quickly.

Handle sourcemaps and chaining

---

readme.md
src/asset-relocator.js
src/utils/sharedlib-emit.js
test/index.test.js

This resolves https://github.com/zeit/ncc/issues/359, firstly implementing a `debugLog` option to determine why certain assets are emitted and secondly to fix the issue by restricting asset emission to the package boundary.
In theory this is a breaking change.

Implement debugLog, restrict asset emission to package boundary

---

readme.md
src/asset-relocator.js
src/utils/static-eval.js
test/unit/process-env/a.js
test/unit/process-env/b.js
test/unit/process-env/input.js
test/unit/process-env/output-coverage.js
test/unit/process-env/output.js

This was originally created to handle https://github.com/zeit/ncc/issues/358, but it would only work if we explicitly add the `FLUENTFFMPEG_COV: false` to the analysis here. I don't think we should treat all unknown process.env properties as falsy, which was the tempting way to do this, but that seems like it would break other things.
Will see if I can work on another approach for https://github.com/zeit/ncc/issues/358.

process.env analysis in require conditionals

---

src/asset-relocator.js
test/unit/express-template-engine/input.js
test/unit/express-template-engine/output-coverage.js
test/unit/express-template-engine/output.js

This adds support for `express.engine` as discussed in https://github.com/zeit/ncc/issues/364.

Support express.engine view engine override

---

src/asset-relocator.js
test/index.test.js
test/unit/process-env/output-coverage.js
test/unit/process-env/output.js

This fixes the regression on the ncc upgrade path for juggling-db.
In the conditional failure handling I was able to remove the explicit Node.js version inlining, but to fully support juggling-db this requires supporting `.json` files in conditional failure paths.

Fixup json import conditional failure

---

src/asset-relocator.js

The level of analysis has finally reached the point where we do need to analyze every single JavaScript file in the build. We slowly expended the regex over time to where that is almost the case already, so it's not such a big change at this point. This is necessary for the ffmpeg integration test to pass.

Relocate all files

---

src/asset-relocator.js
test/unit/require-esm/input.js
test/unit/require-esm/output-coverage.js
test/unit/require-esm/output.js

This resolves https://github.com/zeit/ncc/issues/379 where `require` analysis was being done unnecessarily in ES module files.

Fix invalid shadowDepth access for require

---

src/asset-relocator.js
src/utils/special-cases.js
test/unit/require-wrapper/dep.js
test/unit/require-wrapper/input.js
test/unit/require-wrapper/output-coverage.js
test/unit/require-wrapper/output.js

This adds support for handling the bound require case like https://github.com/zeit/ncc/issues/383.
The approach is very very specific to this case, and in that way is pretty awful, but as per usual the hope that has so far served us well is that as we continue to incorporate cases into the codebase, the generalizations start to become clear as we go, and the analysis naturally becomes more generalized over time.
Already this support was very easy to do because of the above approach working in the past, since the new well-known symbol handlers give us a simple interception method.

Require wrapper support

---

src/asset-relocator.js

This updates the entry handling in this project to support multiple entry builds, including support in the caching and require.main detection.

Add support for multi-entry builds

---

src/utils/sharedlib-emit.js

This fixes a bug in the handling of symlinks output with an assetBase, where the assetBase was not taken into account for the symlink path.
This gets the tests on https://github.com/zeit/ncc/pull/410 to pass.

Include assetBase in symlinks handling

---

src/asset-relocator.js
test/unit/module-require/input.js
test/unit/module-require/output-coverage.js
test/unit/module-require/output.js

The known bindings handling for `'module'` wasn't done quite right, leading to a bug on the ncc build.
This corrects that with the case that was causing the failure in the unit test.

Known bindings regression with 'module' tracking

---

src/asset-relocator.js
test/unit/require-empty/input.js
test/unit/require-empty/output-coverage.js
test/unit/require-empty/output.js

This came up in the Next.js integration work - Webpack will inline errors inside try-catch statements, while our analysis was inlining empty strings through the analysis as if that was a known module path.
By just checking the empty string we should be able to support this Next.js case falling through to the dynamic environment require.

Never inline empty require case

---

src/asset-relocator.js
test/unit/require-wrapper2/dep.js
test/unit/require-wrapper2/input.js
test/unit/require-wrapper2/output-coverage.js
test/unit/require-wrapper2/output.js
test/unit/require-wrapper3/dep.js
test/unit/require-wrapper3/input.js
test/unit/require-wrapper3/output-coverage.js
test/unit/require-wrapper3/output.js

This extends the support and coverage for the require wrapper detection and handling.
It also fixes a bug that was being thrown for invalid wrapper detection cases.

Fixup require wrapper case handling

---

src/asset-relocator.js
test/unit/asset-fs-inline-assign/output-coverage.js
test/unit/asset-fs-inline-assign/output.js
test/unit/asset-fs-inline-path-shadow/output.js
test/unit/dirname-emit/input.js
test/unit/dirname-emit/output-coverage.js
test/unit/dirname-emit/output.js
test/unit/ffmpeg-installer/output-coverage.js
test/unit/ffmpeg-installer/output.js
test/unit/fs-emission/output-coverage.js
test/unit/fs-emission/output.js
test/unit/oracledb/output-coverage.js
test/unit/oracledb/output.js
test/unit/socket.io/output-coverage.js
test/unit/socket.io/output.js

This removes the filtering that restricts emitting any `__dirname` references on their own that aren't analyzable as larger expressions.
The result is the risk of emitting more entire package directories unnecessarily, but this doesn't break anything in the ncc integration tests.

Remove __dirname filtering

---

readme.md
src/asset-relocator.js
test/index.test.js
test/unit/filter-asset-base/input.js
test/unit/filter-asset-base/output-coverage.js
test/unit/filter-asset-base/output.js
test/unit/socket.io/output.js

This allows some new configuration options for asset filter customization:
1. `filterAssetBase` the base path below which assets will never be emitted. This is necessary to fix a now-node bug.
2. `emitDirnameAll` - a boolean option to determine whether it is possible to emit the entire contents of the local directory with just a free `__dirname` referenece.
3. `emitFilterAssetBaseAll` - a boolean option to determine whether it is possible to emit the entire contents of the `filterAssetBase` by just referencing it.
(2) and (3) could be left out of this PR possibly too.

Add asset filter customization

---

readme.md
src/asset-relocator.js

This documents the APIs we've been using for cache persistence and symlink and permission handling.
In addition, it fixes up a cache bug with the public path emission, where we really need to ensure we have a plugin hook to maintain this injection in the fully cached case (as was happening with the bugs on https://github.com/zeit/ncc/pull/442).
This isn't a great API I know, I'm hoping we can improve it. @sokra may have some ideas going forward especially since loaders needing plugin hooks to manage their cache tables seems like a generic problem.

Fixup and document cache attachment

---

readme.md
src/asset-relocator.js

The cache API changes were left out of https://github.com/zeit/webpack-asset-relocator-loader/pull/61 due to some git revert issues between the commits.

Reinclude cache API changes

---

src/asset-relocator.js
test/unit/wildcard-require/output-coverage.js
test/unit/wildcard-require/output.js

This fixes up the wildcard handling to ensure that wildcard matching is done both on the wildcard substitution with and without the default extension applied, to better match standard cases of eg `require('./path/' + dyn)` where `dyn` does not include the file extension.

Fixup wildcard extension handling

---

src/asset-relocator.js

This should fix https://github.com/zeit/ncc-watcher/pull/4.
The issue is that we were not including the relevant `addDependency` calls in the loader to ensure Webpack properly tracks the asset invalidations.

Call addDependency on emitFile calls

---

src/utils/special-cases.js

This updates the special case to handle the 4.x versions, necessary for the v12 update on ncc.

Update oracledb binding path

---

src/utils/wrappers.js
test/unit/jsonc-parse-wrapper/dep.js
test/unit/jsonc-parse-wrapper/input.js
test/unit/jsonc-parse-wrapper/output-coverage.js
test/unit/jsonc-parse-wrapper/output.js

This implements the same UMD wrapper support added in https://github.com/zeit/node-file-trace/pull/109.
As always, it's not ideal maintaining two codebases here, but note how the exact codepaths are different between the projects as well.
I personally don't mind just doubling up as it's quick though.

New UMD wrapper support

---

src/asset-relocator.js

Hello :wave:
In webpack@5.0.0-beta.16 and earlier betas, `compilation.options.entry` looks like this:
```json
{
"bundle-tests.spec":{
"import":[
"/Users/test/bundle-tests.spec.ts"
]
},
"inner-folder/bundle-tests2.spec":{
"import":[
"/Users/test/inner-folder/bundle-tests2.spec.ts"
]
}
}
```
`getEntryIds` doesn't take that into account, and it passes an object  to `resolve.sync`, which always throws `TypeError: Path must be a string.`
This PR also addresses:
```
[DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE_FN] DeprecationWarning: MainTemplate.requireFn is deprecated (use "__webpack_require__")
```
Also, without that patch, `ncc`'s [build](https://github.com/zeit/ncc/blob/master/package.json#L11) [with webpack@5.0.0-beta.16](https://github.com/zeit/ncc/compare/master...yurynix:upgrade-webpack-to-latest …

Compatibility with latest webpack beta 

---

package.json
yarn.lock

When working with code that has empty catch block, I get the following error:
```
(node:31513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
at extractNames (/Users/yurynix/someproject/node_modules/node_modules/@zeit/webpack-asset-relocator-loader/dist/index.js:11469:12)
at /Users/yurynix/someproject/node_modules/node_modules/@zeit/webpack-asset-relocator-loader/dist/index.js:11484:7
at Array.forEach (<anonymous>)
at new Scope (/Users/yurynix/someproject/node_modules/node_modules/@zeit/webpack-asset-relocator-loader/dist/index.js:11483:28)
at Object.enter (/Users/yurynix/someproject/node_modules/node_modules/@zeit/webpack-asset-relocator-loader/dist/index.js:11552:16)
at visit (/Users/yurynix/someproject/node_modules/node_modules/@zeit/webpack-asset-reloc …
```

Upgrade rollup-pluginutils

---

readme.md
src/asset-relocator.js
src/utils/sharedlib-emit.js
test/index.test.js

This renames `relocatorLoader.getAssetPermissions` to `relocatorLoader.getAssetMeta` which then includes both `permissions` and `path` providing the original asset path.
This is necessary to enable subsequent asset processing operations.
Strictly speaking this is a major change so should probably be a bump.

feat: extend asset metadata to include original path

---

src/asset-relocator.js
test/index.test.js

When running subbuild compilations in ncc, we need to be able to get the asset lists for different compilations. This permits a new `compilation` argument to the asset functions that allows passing this information, while remaining backwards compatible with the existing API so it is just a patch release.

Subbuild compilations

---

src/utils/dedupe-names.js
test/unit/dirname-emit-dedupe/input.js
test/unit/dirname-emit-dedupe/output-coverage.js
test/unit/dirname-emit-dedupe/output.js

Exact dir emissions are still linked to their original path, so this handles that case as well.

Fixup exact dir case in directory deduping

---

src/asset-relocator.js
test/unit/asset-fs-array-expr/asset1.txt
test/unit/asset-fs-array-expr/input.js
test/unit/asset-fs-array-expr/output-coverage.js
test/unit/asset-fs-array-expr/output.js

We originally added special handling for array expressions in the execution analysis in https://github.com/vercel/webpack-asset-relocator-loader/commit/fa67f5da991d15427ef85110cc2c24c366d20a48.
This is the reason for the slightly different handling of arrays in the analysis process resulting in non-emission in some cases.
This PR fixes that by ensuring the emit function detects and handles array expression values that are detected down to their sub element assets.

Fixup array expression analysis

---

.github/workflows/prs.yml

This pull request allows us to enforce that pull requests have proper conventional commit titles.

ci: verify pull request titles

---

src/asset-relocator.js
test/index.test.js
test/unit/require-multiassign-inline/a.js
test/unit/require-multiassign-inline/b.js
test/unit/require-multiassign-inline/input.js
test/unit/require-multiassign-inline/output-coverage.js
test/unit/require-multiassign-inline/output.js

In cases like:
```js
var x = './a.js';
if (condition)
x = './b.js';
require(x);
```
we currently follow the pattern of always inlining the last condition (since the analysis isn't smart enough to do any better than that).
This way the require works instead of just bailing as it would with normal webpack so it turns something that definitely doesn't work into something that might work.
This PR extends this inlining case to use the `customEmit` function so that it is possible for users to manually rewrite the emission in these cases, using the best-guess analysis value as the input. It's somewhat of a convoluted API technique, but it gets there in handling the flexibility needed for sass-loader in Next.js.

feat: support customEmit for inlined require analysis

---

src/asset-relocator.js

Hello,
As stated on https://www.npmjs.com/package/node-pre-gyp, `node-pre-gyp` has moved to `@mapbox/node-pre-gyp`. This is breaking relocation of some native modules such as `bcrypt: 5.0.1` so I have added the new scoped package to the list.

fix: scoped version of node-pre-gyp unrecognized

---

package.json
src/asset-relocator.js
src/utils/static-eval.js
test/unit/import-meta-bad-url/asset1.txt
test/unit/import-meta-bad-url/asset2.txt
test/unit/import-meta-bad-url/input.js
test/unit/import-meta-bad-url/output-coverage.js
test/unit/import-meta-bad-url/output.js
test/unit/import-meta-tpl-cnd/asset1.txt
test/unit/import-meta-tpl-cnd/asset2.txt
test/unit/import-meta-tpl-cnd/input.js
test/unit/import-meta-tpl-cnd/output-coverage.js
test/unit/import-meta-tpl-cnd/output.js
test/unit/import-meta-url/asset.txt
test/unit/import-meta-url/input.js
test/unit/import-meta-url/output-coverage.js
test/unit/import-meta-url/output.js
yarn.lock

This adds support for emitting `import.meta.url` asset references including with `new URL` usage. Port of https://github.com/vercel/nft/pull/180.

feat: import.meta.url asset emission support

---

release.config.js

This config is necessary since `semantic-release` doesn't detect the main branch for some reason.
- Docs: [Configuration File](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration-file)
- Related to https://github.com/semantic-release/semantic-release/issues/1581

fix: add release.config.js to configure main

---

package.json
src/asset-relocator.js
yarn.lock

This brings through the same updates from NFT adding support for private fields and eg numeric separators.

feat: update acorn and add private fields support

---

readme.md
src/asset-relocator.js
test/index.test.js
test/unit/esm-dirname/input.js
test/unit/esm-dirname/output-coverage.js
test/unit/esm-dirname/output.js

This adds support for module chunk emission to handle the asset base as relative to `import.meta.url` instead of `__dirname`.

feat: esm output mode for asset relocator chunks

---

src/asset-relocator.js
test/project-chunking/expected.js
test/project-chunking/webpack.config.js

Resolves https://github.com/vercel/webpack-asset-relocator-loader/issues/144.

feat: make plugin options optional

---

src/asset-relocator.js

On windows, one of the unit tests does not pass:
```
● should generate correct output for wildcard2
expect(received).toBe(expected) // Object.is equality
- Expected  - 1
+ Received  + 1
@@ -42,11 +42,11 @@
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
const path = __webpack_require__(622);
- fs.readFileSync(__webpack_require__.ab + "wildcard2/" + unknown + '/asset1.txt');
+ fs.readFileSync(__webpack_require__.ab + "wildcard2/" + unknown + '//asset1.txt');
})();
module.exports = __webpack_exports__;
112 |       .replace(/\r/g, "");
113 |     try {
> 114 |       expect(actual).toBe(expected);
|                      ^
115 |     } catch (e) {
116 |       // useful for updating fixtures
117 …
```

fix: correctly handle Windows path in emitAssetDirectory

---

.github/workflows/ci.yml
jest.config.js
test/project.test.js

Add windows to CI matrix so we can run tests against windows

chore: add windows to CI

---

.github/workflows/ci.yml

chore: update ci to node@14

---

src/asset-relocator.js
test/unit/node-gyp-build-resolve/fake-binding/package.json
test/unit/node-gyp-build-resolve/fake-binding/src/index.js
test/unit/node-gyp-build-resolve/input.js
test/unit/node-gyp-build-resolve/output-coverage.js
test/unit/node-gyp-build-resolve/output.js

This is based on existing PR #168 by @MarshallOfSound
I rebased the original commits except for the one introducing the tests which I have rewritten
Instead of requiring an external library (ffi-napi), I created a dummy binding that node-pre-gyp can use as input with a predictable binding file path that won't depend on the platform.

fix: Use computed node-gyp-build path

---

.github/workflows/ci.yml
src/utils/special-cases.js
test/project-chunking/expected.js
test/project-chunking/main.js
test/project-chunking/package.json
test/project-chunking/packages/sharp.js
test/project-chunking/packages/sharp32.js
test/project-chunking/webpack.config.js
test/project.test.js

The idea is stolen from [nft](https://github.com/vercel/nft/blob/main/src/utils/special-cases.ts#L151), where we introspect package.json to retrieve optional dependencies containing the native addon and relocate them. Following that, I patched the [third item](https://github.com/lovell/sharp/blob/v0.34.2/lib/sharp.js#L16) within the path list, which will be used to load the addon file in the subsequent lines.
Since the prebuilt binaries are available on all platforms I could name, we may ignore the WASM builds. I've added integration tests requiring actual packages, but haven't updated the CI workflow yet, as it would cause longer CI times. The tests include sharp v0.34.2 and v0.32.6 to ensure the new mechanism doesn't affect the existing workflow. I've also run the scripts on both …

fix: support the packaging format of sharp v0.34.x
